fix

diff --git a/.github/workflows/ScalaCI.yml b/.github/workflows/ScalaCI.yml
--- a/.github/workflows/ScalaCI.yml
+++ b/.github/workflows/ScalaCI.yml
@@ -44,15 +44,16 @@ jobs:
 
       - name: Run Test
         if: success() || failure()
-        run: sbt coverage test coverageReport
-
-      - name: Aggregate coverage report
-        if: success() || failure()
-        run: sbt coverageAggregate
-
-      - name: Upload test coverage report
-        if: success() || failure()
-        run: bash <(curl -s https://codecov.io/bash) 
+        run: sbt test
+#        run: sbt coverage test coverageReport
+#
+#      - name: Aggregate coverage report
+#        if: success() || failure()
+#        run: sbt coverageAggregate
+#
+#      - name: Upload test coverage report
+#        if: success() || failure()
+#        run: bash <(curl -s https://codecov.io/bash) 
 
   ci:
     runs-on: ubuntu-20.04
